inj_cora:
  lr: 0.0001
  num_heads: 1
  weight_decay: 2e-5
  max_epoch: 30
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 64
  loss_weight_f: 0
  alpha: 0.8656 # 0.8571
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  highpass_layer_num: 1
  lowpass_layer_num: 2
  high_coe: 0.6
  neighbor_rec_loss_coe: 1
  center_rec_coef: 0.1
inj_amazon:
  lr: 0.0001
  num_heads: 1
  weight_decay: 2e-5
  max_epoch: 30
  num_layers: 2
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 16
  loss_weight_f: -0.01
  alpha: 0.9831  # 0.9453
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  highpass_layer_num: 1
  lowpass_layer_num: 1
  high_coe: 0.6
  neighbor_rec_loss_coe: 0.03
  center_rec_coef: 0.9
weibo:
  lr: 0.0001
  num_heads: 1
  weight_decay: 2e-5
  max_epoch: 30
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gat"
  node_encoder_num_layers: 2
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 1
  num_hidden: 32
  loss_weight_f: 0
  alpha: None  # 0.0099
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  loss_weight_f: -0.1
  highpass_layer_num: 2
  lowpass_layer_num: 2
  neighbor_rec_loss_coe: 1
  high_coe: 0.3
  center_rec_coef: 0.7
reddit:
  lr: 0.001
  weight_decay: 2e-4
  max_epoch: 30
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 2
  attr_decoder_num_layers: 2
  struct_decoder_num_layers: 1
  num_hidden: 16
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  loss_weight_f: -1
  alpha: None # 0.9505
  highpass_layer_num: 2
  lowpass_layer_num: 2
  neighbor_rec_loss_coe: 1
  high_coe: 0.9
  center_rec_coef: 0.7
disney:
  lr: 0.001
  num_heads: 1
  weight_decay: 2e-5
  max_epoch: 30
  num_layers: 2
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  aggr_f: "min"
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  attr_decoder_num_layers: 2
  struct_decoder_num_layers: 1
  num_hidden: 32
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  loss_weight_f: -0.01
  alpha: None # 5.9664e-05
  highpass_layer_num: 2
  lowpass_layer_num: 1
  high_coe: 0.25
  neighbor_rec_loss_coe: 0.5
  center_rec_coef: 0.05
books:
  lr: 0.0001
  num_heads: 1
  weight_decay: 2e-5
  max_epoch: 30
  num_layers: 2
  activation: relu
  optimizer: adam
  alpha_l: 3
  dropout: 0.
  aggr_f: "min"
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 2
  attr_decoder_num_layers: 1
  struct_decoder_num_layers: 2
  num_hidden: 32
  alpha: None # 1.2191e-06
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  loss_weight_f: 0
  highpass_layer_num: 1
  lowpass_layer_num: 2
  high_coe: 0.9
  neighbor_rec_loss_coe: 1
  center_rec_coef: 0.4
enron:
  lr: 0.0001
  weight_decay: 2e-5
  max_epoch: 30
  activation: relu
  optimizer: adam
  dropout: 0.
  attr_encoder: "gcn"
  attr_decoder: "gat"
  struct_decoder: "gcn"
  node_encoder_num_layers: 1
  attr_decoder_num_layers: 2
  struct_decoder_num_layers: 1
  num_hidden: 16
  alpha: None # 0.1236
  model_name: "NKAD"
  loss_f: "add_log_t_entropy"
  T_f: 2
  highpass_layer_num: 1
  lowpass_layer_num: 1
  high_coe: 0.1
  neighbor_rec_loss_coe: 1
  center_rec_coef: 0.1
